version: 2.1

commands:
  run-tox:
    description: "Run tox"
    parameters:
      version:
        type: string
      sphinx-version:
        type: string
        default: "21,22,23,24,30,31,32,33,34,35,40,41,42,43,44,latest"
    steps:
      - checkout
      # NOTE: update tox to tox<5 when https://github.com/tox-dev/tox/issues/2850
      # is fixed.
      - run: pip install --user 'tox<4'
      - run: tox -e "<<parameters.version>>-sphinx{<<parameters.sphinx-version>>}"

jobs:
  py27:
    docker:
      - image: 'cimg/python:2.7'
    steps:
      - run-tox:
          version: py27
          sphinx-version: 15,16,17,18
  py36:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - run-tox:
          version: py36
          sphinx-version: 15,16,17,18
  py37:
    docker:
      - image: 'cimg/python:3.7'
    steps:
      - run-tox:
          version: py37
  py38:
    docker:
      - image: 'cimg/python:3.8'
    steps:
      - run-tox:
          version: py38
  py39:
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - run-tox:
          version: py39

  py310:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - run-tox:
          version: py310
          sphinx-version: 42,43,44,latest

  lint:
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - checkout
      - run: pip install --user tox
      - run: tox -e lint

workflows:
  version: 2
  tests:
    jobs:
      - lint
      - py310
      - py39
      - py38
      - py37
      - py36
      - py27
